default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do
    run_tests(scheme: "PlainText")
   end

  desc "Check style and conventions"
  lane :lint do
    swiftlint(strict: true)
  end

  desc "Increment build and version number and commit"
  lane :version_bump do |options|
    version_number = options[:version_number]
    puts version_number
    build_number = increment_build_number_in_xcodeproj
    increment_version_number_in_xcodeproj(
      version_number: version_number
    )
    message = "build: bumped version to " + version_number + " and build number to " + build_number
    puts message
    commit_version_bump(
      message: message,
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean
    build_app(scheme: "PlainText")
    upload_to_testflight
  end

  desc "Push a new release build to the App Store"
  lane :release do
    ensure_git_status_clean
    build_app(scheme: "PlainText")
    upload_to_app_store(skip_metadata: true, skip_screenshots: true)
  end

end
